MongoDB:
  ENABLED: false # Enable MongoDB database.
  URI: "" # Connection URI/String to MongoDB database.
  DATABASE: "" # Database name of MongoDB database

DefaultHealth: 20

HeartRecipe:
  Properties:
    ItemType: "PAPER"
    Name: "Heart"
    Lore: ["TT", "PP"]
    CustomModel: true
      ModelData: 123456

  #Crafting table representation.
  #  +---+---+---+
  #  | A | B | C |
  #  +---+---+---+
  #  | D | E | F |
  #  +---+---+---+
  #  | G | H | I |
  #  +---+---+---+

  #Heart item recipe, it is a shaped recipe.
  Recipe:
    A: "DIAMOND"
    B: "GOLD_INGOT"
    C: "DIAMOND"
    D: "GOLD_INGOT"
    E: "NETHER_STAR"
    F: "GOLD_INGOT"
    G: "DIAMOND"
    H: "GOLD_INGOT"
    I: "DIAMOND"