Version: 3
Language: en

DATABASE:
  ENABLED:
  ADDRESS:
  PORT:
  DATABASE:
  USERNAME:
  PASSWORD:

DefaultHealth: 20
DisableTotem: true
DisableMilkCure: true

Heart:
  Properties:
    ItemType: "PAPER"
    Name: "<gradient:#e01e37:#e01e37>Heart</gradient>"
    Lore:
      - "<gradient:#f89999:#f6c0ba>This is a placeholder heart.</gradient>"
      - "<gradient:#f89999:#f6c0ba>This consumable heart will give you <hp> heart points.</gradient>"
      - "<gradient:#f89999:#f6c0ba>This will be turned into a normal, blessed or cursed heart after crafting.</gradient>"
    ModelData: 123456
#Heart item recipe, it is a shaped recipe.
  Recipe:
    A: "DIAMOND"
    B: "GOLD_INGOT"
    C: "DIAMOND"
    D: "GOLD_INGOT"
    E: "NETHER_STAR"
    F: "GOLD_INGOT"
    G: "DIAMOND"
    H: "GOLD_INGOT"
    I: "DIAMOND"
#Crafting table representation.
#  +---+---+---+
#  | A | B | C |
#  +---+---+---+
#  | D | E | F |
#  +---+---+---+
#  | G | H | I |
#  +---+---+---+

# What happens after player looses all hearts.
#Valid values are,
#DEAD = Spectates own body npc,
#SPECTATING = Roams around freely in spectator mode,
#BANNED = Gets banned, only works if death bans are enabled.
LifeState: "BANNED"

Ban-Command-URI: 'ban %player% 3d [LifeSteal] - Eliminated. -s'

# State how many hearts players should lose on death.
# 2 heart points = 1 whole heart.
HeartsToLose: 2

# State how many hearts points players gain on heart item consume.
# 2 heart points = 1 whole heart.
HeartsToGain: 2