version: "2.0"
MongoDB:
  ENABLED: false # Enable MongoDB database.
  URI: "" # Connection URI/String to MongoDB database.
  DATABASE: "" # Database name of MongoDB database

DefaultHealth: 20

HeartRecipe:
  Properties:
    ItemType: "PAPER"
    Name: "<RED>Heart</RED>"
    Lore: ["TT", "This consumable heart will give you <hp> heart points." , "PP"]
    CustomModel: true
    ModelData: 123456

  #Crafting table representation.
  #  +---+---+---+
  #  | A | B | C |
  #  +---+---+---+
  #  | D | E | F |
  #  +---+---+---+
  #  | G | H | I |
  #  +---+---+---+

  #Heart item recipe, it is a shaped recipe.
  Recipe:
    A: "DIAMOND"
    B: "GOLD_INGOT"
    C: "DIAMOND"
    D: "GOLD_INGOT"
    E: "NETHER_STAR"
    F: "GOLD_INGOT"
    G: "DIAMOND"
    H: "GOLD_INGOT"
    I: "DIAMOND"

# What happens after player looses all hearts.
#Valid values are,
#DEAD = Spectates own body npc,
#SPECTATING = Roams around freely in spectator mode,
#BANNED = Gets banned, only works if death bans are enabled.
LifeState: "BANNED"

# State how many hearts players should lose on death.
# 2 heart points = 1 whole heart.
HeartsToLose: 2

# State how many hearts points players gain on heart item consume.
# 2 heart points = 1 whole heart.
HeartsToGain: 2