name: Latest release

on:
  release:
    types: [published]

jobs:
  create-release:
    name: Changes any published release ttag with `latest`
    runs-on: ubuntu-latest

    steps:
      - name: Latest tag
        uses: EndBug/latest-tag@v1.5.0
